# see http://about.travis-ci.org/docs/user/languages/php/
language: php
php:
  - 5.6

git:
  depth: 5

before_install:
  - composer self-update

install:
  - composer install
  - composer npm-install

before_script:
  - composer --version
  - composer versions

script:
  - composer validate --no-interaction
  # Run all lint tests.
  - composer test

#End.
