# see http://about.travis-ci.org/docs/user/languages/php/
language: php
php:
  - 7.0
  #-5.6

git:
  depth: 5

before_install:
  - nvm install v4.4
  - npm install npm -g
  - npm --version

install:
  - composer install
  - composer npm-install

script:
  - composer validate --no-interaction
  # Build and run tests.
  - composer test

after_script:
  #- composer --version
  #- grunt exec:versions
  cat uglify-theme-json

#End.
