# see http://about.travis-ci.org/docs/user/languages/php/
language: php
php:
  - 5.6

git:
  depth: 5

before_install:
  - composer self-update --preview
  - npm install npm -g

install:
  - composer install
  - composer npm-install

script:
  - composer validate --no-interaction
  # Build and run tests.
  - composer test

after_script:
  - composer --version
  - grunt exec:versions

#End.
